#!/usr/bin/env python3

from argparse import ArgumentParser
from lxml import etree
import requests
import time
import json

SPEEDTEST_CONFIG_URL_XML = "https://www.speedtest.net/api/android/config.php"
SPEEDTEST_CONFIG_URL_JSON = "https://www.speedtest.net/api/js/config-sdk.php"

SPEEDTEST_REQ_DELAY = 1

SPEEDTEST_DEFAULT_USERAGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36"


class Server:
    def __init__(self, attrib):
        self.server_id = int(attrib["id"])
        self.latitude = attrib["lat"]
        self.longtitude = attrib["lon"]
        self.location_name = attrib["name"]
        self.sponsor = attrib["sponsor"]
        self.test_url = attrib["url"]
        self.test_host = attrib["host"]
        self.country_code = attrib.get("cc")
        self.https_functional = attrib.get("https_functional")

    def __hash__(self):
        return hash(self.server_id)

    def __eq__(self, other):
        if not isinstance(other, Server):
            return False

        return self.server_id == other.server_id

    def to_dict(self):
        return vars(self)


class ServerXMLParser:
    class ServerAccumulator:
        def __init__(self):
            self.servers = []

        def start(self, tag, attrib):
            if tag == "server":
                self.servers.append(Server(attrib))

        def close(self):
            server_list = list(self.servers)
            self.servers.clear()
            return server_list

    def __init__(self):
        self._xml_parser = etree.XMLParser(target=self.ServerAccumulator())

    def __call__(self, servers_xml):
        return etree.fromstring(servers_xml, self._xml_parser)


class ServerJSONParser:
    def __call__(self, servers_json):
        return [ Server(server_obj) for server_obj in json.loads(servers_json)["servers"] ]


def old_api_query_generator():
    page_size = -1
    page_offset = 0

    while page_size != 0:
        page_size = yield SPEEDTEST_CONFIG_URL_XML, { "appversion": "5.0.0", "offset": page_offset }
        page_offset += page_size


def new_api_query_generator(query_plan):
    for query_loc in query_plan:
        yield SPEEDTEST_CONFIG_URL_JSON, { "engine": "js", "limit": 100, "lat": query_loc["latitude"], "lon": query_loc["longtitude"] }


def fetch_servers(query_gen, parser, user_agent):
    with requests.Session() as http_session:
        result = []
        seen = set()

        try:
            query_url, query_params = query_gen.send(None)

            last_req_time = 0

            while True:
                time.sleep(max(0, SPEEDTEST_REQ_DELAY - (time.time() - last_req_time)))

                last_req_time = time.time()

                http_response = http_session.get(query_url, params=query_params, headers={
                    "User-Agent": user_agent
                })

                if http_response.status_code != 200:
                    print(f"Received HTTP {http_response.status_code}. Retrying...")
                    continue

                parsed_list = parser(http_response.content)

                for server in parsed_list:
                    if not isinstance(server, Server):
                        raise ValueError("Parser should return an instance of Server")

                    if server not in seen:
                        seen.add(server)
                        result.append(server)

                print(f"Fetched {len(result)} servers so far")

                query_url, query_params = query_gen.send(len(parsed_list))
        except StopIteration:
            return result


def main():
    args_parser = ArgumentParser()
    args_parser.add_argument("--plan", help="Query plan file")
    args_parser.add_argument("--output", help="Output JSON file", required=True)
    args_parser.add_argument("--user-agent", help="HTTP User-Agent header value", default=SPEEDTEST_DEFAULT_USERAGENT)
    args = args_parser.parse_args()

    with open(args.output, "w") as out_fd:
        if args.plan is not None:
            with open(args.plan) as plan_fd:
                query_plan = json.load(plan_fd)

            server_list = fetch_servers(new_api_query_generator(query_plan), ServerJSONParser(), args.user_agent)
        else:
            server_list = fetch_servers(old_api_query_generator(), ServerXMLParser(), args.user_agent)

        json.dump([ server.to_dict() for server in server_list ], out_fd)


if __name__ == "__main__":
    main()
